### ISSUE TITLE
AspNetCore5 build

### ISSUE THREAD

**Issue by avanderhoorn** [damianh/LibOwin#10]
Switch over to new AspNet5 project structure so we can have an out of the box .net45, AspNet50 and AspNetCore50 build.

**Comment by horsdal** [comment]
Still on hold?
Would you accept a PR?

I think there a few things that needs doing here:

 * Move to `project.json`
 * Make it compile on .NET core
 * Change NuSpec to match NuGet3 style for source packages since that is all dnu/dotnet-cli will support

**Comment by damianh** [comment]
Hi  @horsdal ! Will definitely accept and appreciate a PR :+1:
